# GENERATE TIME: Fri Mar  3 15:38:53 2023
# CMD:
# train.py -expe_opt options/expe/NATIR/NATIR_LSR.yml -task_opt options/task/LSR_x4.yml

# GENERATE TIME: Mon Feb 27 14:33:11 2023
# CMD:
# train.py -expe_opt options/expe/NATIR/NATIR_LSR.yml -task_opt options/task/LSR_x4.yml

# general settings #####################################################################################################
name: diNATIR
model_type: IRModel
num_gpu: 1  # 0 for cpu mode
manual_seed: 42
bit: 8 # data type
mixed_fp: true

# network structure ####################################################################################################
network_g:
  type: _NATIR
  window_size: 13
  img_range: 1.
  depths: [6, 6, 6, 6]
  embed_dim: 60
  num_heads: [6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffledirect'
  dilations: [1,2,1,3,1,4]
  use_checkpoint: true

# path #################################################################################################################
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~


# training settings ####################################################################################################
train:
  # basic setting
  gt_size: 256
  batch_size_per_gpu: 64
  total_iter: 500000

  # optimizer setting
  optim_g:
    type: Adam
    lr: !!float 2e-4
    weight_decay: 0
    betas: [0.9, 0.99]

  scheduler:
    type: MultiStepLR
    milestones: [250000, 400000, 450000, 475000]
    gamma: 0.5

  # loss setting
  pixel_opt:
    type: L1Loss
    loss_weight: 1.0
    reduction: mean


# validation settings ##################################################################################################
val:
  val_freq: 5000
  save_img: false
  suffix: ~

  metrics:
    psnr:
      type: calculate_psnr
      crop_border: 4
      test_y_channel: true
    ssim:
      type: calculate_ssim
      crop_border: 4
      test_y_channel: true